#!/usr/bin/env ruby

# frozen_string_literal: true

require "dotenv/load"
require "twitch/chat"

# rubocop:disable Metrics/BlockLength FIXME
client = Twitch::Chat::Client.new(
  channel: ENV["TWITCH_CHANNEL"],
  nickname: ENV["TWITCH_USERNAME"],
  password: ENV["TWITCH_PASSWORD"],
) do
  on(:connected) do
    send_message "Hi guys!"
  end

  on(:subscribe) do |user|
    client.send_message "Hi #{user}, thank you for your subscription"
  end

  on(:slow_mode) do
    send_message "Slow down guys"
  end

  on(:subscribers_mode_off) do
    send_message "FREEEEEDOOOOOM"
  end

  on(:message) do |message|
    send_message "Current time: #{Time.now.utc}" if message.text == "!time"
  end

  on(:message) do |message|
    if message.text.include?("Hi fullstacklive")
      send_message "Hi #{message.user}!"
    end
  end

  on(:message) do |message|
    if message.text == "!moderators"
      send_message channel.moderators.join(", ")
    end
  end

  on(:new_moderator) do |user|
    send_message "#{user} is our new moderator"
  end

  on(:remove_moderator) do |user|
    send_message "#{user} is no longer moderator"
  end

  on(:disconnect) do
    send_message "Bye guys!"
  end
end
# rubocop:enable Metrics/BlockLength

client.run!
